### PR TITLE
Modifications

### PR DESCRIPTION
**Pull request by glixx**
Update desktop files from transifex
Mark as translatable
Run app without Welcome
Update translations from transifex
Install svg icon in hicolor dir
Add and install hicolor icons
Update spec file
Fix POT file creating (rename .pyw into .py)
Update README
Delete shebang (https://fedoraproject.org/wiki/Packaging_tricks)
Increase release and year
Other way for creating POT file by symlink
Update the icon cache for fedora spec file
Update German and Swedish translations
Update Changelog for 1.43.6

### CODE REVIEW

**Comment by stewartadam** [comment]
Happy new year, and thank you for preparing this! I've reviewed the changes and it looks mostly good - I've made a comment or two on specific commits.

**Comment by glixx** [comment]
Happy new year and Merry Christmas! Thanks for your application. I'll prepare new pull request with new translations when you'll apply this one. After new version can be released. Please wait me and do not release. I want to build package for Mageia after modifications and with the latest translations.

**Comment by glixx** [comment]
Hi stewartadam,
Will you push now?

**Comment by stewartadam** [comment]
Work is keeping me busy, I'll only get a chance to return to this on the weekend... I have to update rebuild the PDF/HTML documentation prior to release as well as double-check the POT file with pyw.

**Comment by stewartadam** [comment]
Merged, and with a few other changes, released 1.43.6. Thank you!

**Pull request merged**
